### ISSUE TITLE
ExecuteDataSet Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by ghd258** [Chavoshi/EnterpriseLibrary.NetCore#13]
private static void TestMySqlDataSet()
        {
            const string sqlCmd = @"Select * from  City
                                    ";
            DatabaseFactory.SetDatabaseProviderFactory(new DatabaseProviderFactory(new SystemConfigurationSource(false).GetSection), false);
            Database db = DatabaseFactory.CreateDatabase("BizDbMySql");

            using (DbCommand cmd = db.GetSqlStringCommand(sqlCmd))
            {
                try
                {                   
                    db.ExecuteDataSet(cmd);
                }
                catch (Exception ex)
                {
                    throw;
                }
            }
        }

System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Microsoft.Practices.EnterpriseLibrary.Data
  StackTrace:
   at Microsoft.Practices.EnterpriseLibrary.Data.Database.DoLoadDataSet(IDbCommand command, DataSet dataSet, String[] tableNames) in J:\EnterpriseLibrary.NetCore-master\Source\Data Access Application Block\Data\Database.cs:line 447
   at Microsoft.Practices.EnterpriseLibrary.Data.Database.LoadDataSet(DbCommand command, DataSet dataSet, String[] tableNames) in J:\EnterpriseLibrary.NetCore-master\Source\Data Access Application Block\Data\Database.cs:line 1304
   at Microsoft.Practices.EnterpriseLibrary.Data.Database.LoadDataSet(DbCommand command, DataSet dataSet, String tableName) in J:\EnterpriseLibrary.NetCore-master\Source\Data Access Application Block\Data\Database.cs:line 1257
   at Microsoft.Practices.EnterpriseLibrary.Data.Database.ExecuteDataSet(DbCommand command) in J:\EnterpriseLibrary.NetCore-master\Source\Data Access Application Block\Data\Database.cs:line 520
   at EnterpriseLibrary.Test.MySql.Program.TestMySqlDataSet() in J:\EnterpriseLibrary.NetCore-master\Examples\EnterpriseLibrary.Test.MySql\EnterpriseLibrary.Test.MySql\Program.cs:line 67
   at EnterpriseLibrary.Test.MySql.Program.Main(String[] args) in J:\EnterpriseLibrary.NetCore-master\Examples\EnterpriseLibrary.Test.MySql\EnterpriseLibrary.Test.MySql\Program.cs:line 14

**Comment by Chavoshi** [comment]
This is a known issue in MySqlClientFactory which is reported in [MySql forum](https://bugs.mysql.com/bug.php?id=88660).
As described there the DbProviderFactory methods are not overridden properly.

In order to fix the problem you can follow  **Toras Nithou** solution:
https://github.com/toras9000/MySqlConnectorBugAvoid/tree/master/MySqlConnectorBugAvoid

It is also necessary to use the latest version of **MySql.Data**, as **DataAdapter** newly added to its package.
You can check the test project as well as I've changed it with these changes.
