### ISSUE TITLE
Cannot use Caching 5 with Data 6.1 RC

### ISSUE THREAD

**Issue by memark** [Chavoshi/EnterpriseLibrary.NetCore#34]
Trying out the new Data 6.1 RC. It works fine by itself. So does Caching 5. But combined, there is a reference conflict.

Repro:

**Project.csproj**
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net461</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommonServiceLocator.NetCore" Version="1.3.1" />
    <PackageReference Include="EnterpriseLibrary.Caching.NetCore" Version="5.0.512" />
    <PackageReference Include="EnterpriseLibrary.Data.NetCore" Version="6.1.10-rc" />
  </ItemGroup>

</Project>
```

**App.config**
```
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  
  <configSections>
    <section name="cachingConfiguration" type="Microsoft.Practices.EnterpriseLibrary.Caching.Configuration.CacheManagerSettings, Microsoft.Practices.EnterpriseLibrary.Caching, Version=5.0.512.0, Culture=neutral, PublicKeyToken=null" />
  </configSections>

  <cachingConfiguration defaultCacheManager="Cache Manager">
    <cacheManagers>
      <add name="Cache Manager" type="Microsoft.Practices.EnterpriseLibrary.Caching.CacheManager, Microsoft.Practices.EnterpriseLibrary.Caching, Version=5.0.512.0, Culture=neutral, PublicKeyToken=null" backingStoreName="Null Storage"
           expirationPollFrequencyInSeconds="60" maximumElementsInCacheBeforeScavenging="1000" numberToRemoveWhenScavenging="10" />
    </cacheManagers>
    <backingStores>
      <add name="Null Storage" type="Microsoft.Practices.EnterpriseLibrary.Caching.BackingStoreImplementations.NullBackingStore, Microsoft.Practices.EnterpriseLibrary.Caching, Version=5.0.512.0, Culture=neutral, PublicKeyToken=null" />
    </backingStores>
  </cachingConfiguration>

  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Practices.EnterpriseLibrary.Common" publicKeyToken="null" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-6.1.15.12" newVersion="6.1.15.12" />"
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
  
</configuration>
```

**Program.cs**
```
using Microsoft.Practices.EnterpriseLibrary.Caching;
using System;

namespace EntLibCachingConflict
{
    class Program
    {
        static void Main()
        {
            var cacheManager = CacheFactory.GetCacheManager();
            Console.WriteLine($"cacheManager: {cacheManager}");
        }
    }
}
```

Run the program. It fails with exception

> System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Practices.EnterpriseLibrary.Common, Version=6.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at Microsoft.Practices.EnterpriseLibrary.Caching.CacheFactory.InnerGetCacheManager(String cacheManagerName)
   at EntLibCachingConflict.Program.Main()

(When downgrading to Data 6.0.1313, it works.)

**Comment by Chavoshi** [comment]
The caching block is not using RC version is not released yet and still using the old common. Creating the new package is in progress.

**Comment by memark** [comment]
@Chavoshi Thanks for the info. Any ETA on that corresponding Caching version?

**Comment by Chavoshi** [comment]
👍 
I'm trying to roll it out by end of March.

**Comment by memark** [comment]
Just a ping here @Chavoshi that it would be much appreciated!

**Comment by memark** [comment]
@Chavoshi Any update?

**Comment by Chavoshi** [comment]
@memark, I'm gonna finalize it in couple of days and it'll be up by mid of April. Sorry for the delay as I was really busy in the last 6 months.

**Comment by memark** [comment]
@Chavoshi Any update?

**Comment by memark** [comment]
@Chavoshi PLS provide an update. If you decided to abandon this project, it's totally fine. It would just be good to know, since then we'll have to find another way to migrate our solution.

**Comment by Chavoshi** [comment]
@memark, Actually converting the caching and cryptography modules were far complex than my expectations. In fact upgrading the Unity to version 5 has made the common v6 completely incompatible with common v5. So for last couple of months I was struggling with making them compatible with each other, and finally I have given up and decided to convert the common v5 completely as an standalone branch, but as we are going to make caching and other v6 blocks work together, the new v5 package and its DLLs have to come with different names.

On the other hand, Microsoft reserved the prefix **EnterpriseLibrary.***, so I am not able to push any new package name with this prefix, as I am currently pushing the packages in this format: EnterpriseLibrary.**.NetCore 😡

But I want you to make sure I am not going to abandon this project and I am close to finish.
The only problem is I am currently the only contributor  on this project and it makes everything tough.

**Comment by memark** [comment]
@Chavoshi How are things going? I can see this must be a bit hard for you!
